galaxy_info:
  author: vkill
  description:
  company: vkill

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2

  platforms:
  - name: Ubuntu
    versions:
    - trusty

  galaxy_tags:
    - sshd

dependencies: []
